[package]
name = "nhk_now"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "^0.4" }
clap = { version = "^4.1", features = ["derive", "env"] }
dioxus = { version = "^0.3" }
dioxus-desktop = { version = "^0.3" }
hyper = { version = "^0.14", features = ["full"] }
hyper-tls = { version = "^0.5" }
reqwest = "0.11.16"
serde_json = { version = "^1.0" }
tokio = { version = "^1.26", features = ["full"] }
